name: POC

on:
  workflow_dispatch:
    inputs:
      android:
        description: 'android'
        required: true
        default: true
        type: boolean
      ios:
        description: 'ios'
        required: true
        default: true
        type: boolean
      qa:
        description: 'qa'
        required: true
        default: true
        type: boolean
      prod:
        description: 'prod'
        required: true
        default: true
        type: boolean

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Requires at least one platform
        run: echo "::error title=Requires at least one platform::please choose android/ios" && exit 1
        if: ${{ !inputs.android && !inputs.ios }}

      - name: Requires at least one environment
        run: echo "::error title=Requires at least one environment::please choose qa/prod" && exit 1
        if: ${{ !inputs.qa && !inputs.prod }}

      - name: Prints 'inputs'
        env:
          INPUTS_JSON: ${{ toJSON(inputs) }}
        run: |
          echo '# Deployment' >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY
          echo '## Inputs' >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY
          echo '```json' >> $GITHUB_STEP_SUMMARY
          echo $INPUTS_JSON >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

  android-qa:
    runs-on: ubuntu-latest
    if: inputs.android && inputs.qa
    needs: setup
    steps:
      - name: android-qa
        run: echo "android-qa"

  android-prod:
    runs-on: ubuntu-latest
    if: inputs.android && inputs.prod
    needs: android-qa
    steps:
      - name: android-prod
        run: echo "android-prod"

  ios-qa:
    runs-on: ubuntu-latest
    needs: setup
    if: inputs.ios && inputs.qa
    steps:
      - name: ios-qa
        run: echo "ios-qa"

  ios-prod:
    runs-on: ubuntu-latest
    needs: ios-qa
    if: inputs.ios && inputs.prod
    steps:
      - name: ios-prod
        run: echo "ios-prod"
