# This is a workflow for testing GitHub Actions.
name: Test

on:
  # push:
  #   branches:
  #     - master

jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 30

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'

      - name: Dump job context
        run: echo '${{ toJSON(job) }}'

      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'

      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'

      - name: Print git information
        run: |
          echo "remote: $(git remote get-url origin)"
          echo "branch: $(git rev-parse --abbrev-ref HEAD)"
          echo "commit: $(git rev-parse --short HEAD)"

      - name: print infos
        run: |
          echo "${{ github.ref_type }}: ${{ github.ref }}"
          echo "commit: ${{ github.sha	}}"

      - name: failed
        run: exit 1

      # - name: Send custom JSON data to Slack workflow
      #   id: slack
      #   uses: slackapi/slack-github-action@v1.23.0
      #   with:
      #   # For posting a rich message using Block Kit
      #     payload: |
      #       {
      #         "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
      #         "blocks": [
      #           {
      #             "type": "section",
      #             "text": {
      #               "type": "mrkdwn",
      #               "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
      #             }
      #           }
      #         ]
      #       }
      #   env:
      #     SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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 # channel:app
      #     SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

      - name: if canceled
        if: ${{ cancelled() }}
        run: echo "Canceled!"

      - name: The demo step has failed
        if: ${{ failure() }}
        run: echo "failure"

      - name: FINISHED 🎉
        if: ${{ success() }}
        run: echo "FINISHED 🎉"
