# This is a workflow for testing GitHub Actions.
name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: Dump secrets context
        run: echo $REPO_SECRET
        env:
          REPO_SECRET: ${{ secrets.REPO_SECRET_1 }}

      - name: Dump secrets context
        run: echo '${{ toJSON(secrets) }}'

      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'

      - name: Dump job context
        run: echo '${{ toJSON(job) }}'

      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'

      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'

      - name: print infos
        run: |
          echo "repo: ${{ github.repository }}"
          echo "${{ github.ref_type }}: ${{ github.head_ref || github.ref_name }}"
          echo "commit: ${{ github.sha	}}"

#       - name: failed
#         run: exit 1

      - name: if canceled
        if: ${{ cancelled() }}
        run: echo "Canceled!"

      - name: The demo step has failed
        if: ${{ failure() }}
        run: echo "failure"

      - name: FINISHED 🎉
        if: ${{ success() }}
        run: echo "FINISHED 🎉"
