# This is a workflow for testing GitHub Actions.
name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: Dump secrets context
        run: echo $REPO_SECRET
        env:
          REPO_SECRET: ${{ secrets.REPO_SECRET_1 }}

      - name: Dump secrets context
        run: echo '${{ toJSON(secrets) }}'

      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'

      - name: Dump job context
        run: echo '${{ toJSON(job) }}'

      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'

      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'

      # - name: print infos
      #   run: |
      #     echo "repo: ${{ github.repository }}"
      #     echo "${{ github.ref_type }}: ${{ github.head_ref || github.ref_name }}"
      #     echo "commit: ${{ github.sha	}}"

#       - name: failed
#         run: exit 1

      - name: if canceled
        if: ${{ cancelled() }}
        run: echo "Canceled!"

      - name: The demo step has failed
        if: ${{ failure() }}
        run: echo "failure"

      - name: Generate release message for Slack
        id: generate-release-message
        run: |
          export APP_VERSION=1.10.0
          export APP_BUILD_NUMBER=97
          export RELEASE_NOTE_LINK="https://github.com/tracmo/tracmo_issues/issues?q=release+seniorcare+$APP_VERSION"
          echo "app-version=$APP_VERSION" >> $GITHUB_OUTPUT
          echo "app-build-number=$APP_BUILD_NUMBER" >> $GITHUB_OUTPUT
          echo "release_note-link=$RELEASE_NOTE_LINK" >> $GITHUB_OUTPUT
          echo "release-message=:seniorcare: SeniorCare $APP_VERSION+$APP_BUILD_NUMBER <$RELEASE_NOTE_LINK|Release Note>" >> $GITHUB_OUTPUT

      - name: condition 1
        if: runner.os == 'Windows'
        run: echo "The operating system on the runner is $env:RUNNER_OS."

      - name: condition 2
        if: runner.os != 'Windows'
        run: echo "The operating system on the runner is not Windows, it's $RUNNER_OS."

      - name: FINISHED 🎉
        if: ${{ success() }}
        run: |-
          echo "## Release 🎉" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          echo "- Repo: ${{ github.repositoryUrl }}" >> $GITHUB_STEP_SUMMARY
          echo "- ${{ github.ref_type }}: ${{ github.head_ref || github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- commit: ${{ github.sha	}}" >> $GITHUB_STEP_SUMMARY
          echo "- App Version: ${{ steps.generate-release-message.outputs.app-version }}" >> $GITHUB_STEP_SUMMARY
          echo "- App Build: ${{ steps.generate-release-message.outputs.app-build-number }}" >> $GITHUB_STEP_SUMMARY
          echo "- [Release Note](${{ steps.generate-release-message.outputs.release_note-link }})" >> $GITHUB_STEP_SUMMARY
