name: test for workflow_dispatch

on:
  workflow_dispatch:
    inputs:
      version:
        description: "tag version"
        required: true
        default: "1.0.0+1"
      is_pre_release:
        description: "pre-release or release, if true, is pre-release"
        required: true
        type: boolean
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ inputs.version }}
          echo ${{ inputs.is_pre_release }}

      - name: Set version number
        run: |
          $version = "3.2."+(4000+$($Env:GITHUB_RUN_NUMBER))+".0"
          echo $version
          echo "VERSION_NUMBER=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append

      - name: View context attributes
        uses: actions/github-script@v6
        with:
          script: |
            const { FIRST_NAME, LAST_NAME } = process.env
            console.log(`Hello ${FIRST_NAME} ${LAST_NAME}`)

            console.log(context)
